# Generated by Django 5.2.9 on 2025-12-20 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Liga/Copa')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador URL')),
                ('api_id', models.IntegerField(unique=True, verbose_name='ID en API Football')),
                ('type', models.CharField(choices=[('LEAGUE', 'Liga'), ('CUP', 'Copa')], default='LEAGUE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('flag_code', models.CharField(max_length=5, verbose_name='Código Bandera')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Escudo URL')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha del partido')),
                ('status', models.CharField(default='SCHEDULED', max_length=20)),
                ('round_name', models.CharField(max_length=50, verbose_name='Ronda / Fecha')),
                ('home_goals', models.IntegerField(blank=True, null=True, verbose_name='Goles Local')),
                ('away_goals', models.IntegerField(blank=True, null=True, verbose_name='Goles Visitante')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.competition', verbose_name='Competición')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team', verbose_name='Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_home', models.IntegerField(verbose_name='Predicción Local')),
                ('predicted_away', models.IntegerField(verbose_name='Predicción Visitante')),
                ('points', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Torneo')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código de Invitación')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Imagen (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_round', models.CharField(blank=True, max_length=50, null=True, verbose_name='Desde la Ronda')),
                ('end_round', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasta la Ronda')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition', verbose_name='Liga/Copa Base')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Aprobación'), ('ACCEPTED', 'Aceptado / Jugando'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Torneo',
                'verbose_name_plural': 'Miembros de Torneo',
                'unique_together': {('tournament', 'user')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='members',
            field=models.ManyToManyField(related_name='tournaments', through='core.TournamentMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
