# Generated by Django 5.2.9 on 2025-12-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Escudo URL'),
        ),
    ]
