# Generated by Django 5.2.9 on 2025-12-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prediction_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=20),
        ),
    ]
